ChuangShun/src/nba_news/api/urls.py
from django.conf.urls import url

from django.views.generic.base import RedirectView

from .views import (
    NewListAPIView,
    NewDetailAPIView
    )

urlpatterns = [
    url(r'^$', NewListAPIView.as_view(), name='list'), # /api/tweet/
    url(r'^(?P<pk>\d+)/$', NewDetailAPIView.as_view(), name='api-detail'),

]

ChuangShun/src/nba_news/urls.py
from django.conf.urls import url

from .views import nba

urlpatterns = [
    url(r'^$', nba, name='nba'), #/
]

ChuangShun/src/web_scraping/urls.py
from django.conf.urls import url, include
from django.contrib import admin


from django.conf import settings
from django.conf.urls.static import static

from .views import home, detail


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home, name='home'),
    url(r'^detail/(?P<id>\d+)/$', detail, name='detail'),
    url(r'^nba-news/', include('nba_news.urls', namespace='nba-news')),
    url(r'^api/nba-news/', include('nba_news.api.urls', namespace='nba-news-api')),

]



if settings.DEBUG:
    urlpatterns += (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))

ChuangShun/src/nba_news/models.py
from django.db import models
from django.utils import timezone
from django.core.urlresolvers import reverse
from django.db.models.signals import post_save


class New (models.Model):
    unique_id = models.CharField(max_length=10, primary_key=True, default='')
    user = models.CharField(max_length=50, default='')
    title        =  models.CharField(max_length=200, default='')
    content      =  models.TextField(null=True)
    image_link   = models.TextField(null=True)
    created_date =  models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.title)

    def get_absolute_url(self):
        return "/detail/%s/" %(self.unique_id)


def post_save_user_receiver(sender, instance, created, *args, **kwargs):
    print( instance.unique_id )
    print( instance.title)
    print( '\n' )


post_save.connect(post_save_user_receiver, sender=New)

ChuangShun/src/nba_news/api/views.py
from rest_framework import generics


from nba_news.models import New
from .serializers import NewModelSerializer
from .pagination import StandardResultsPagination

class NewListAPIView(generics.ListAPIView):
    serializer_class = NewModelSerializer
    pagination_class = StandardResultsPagination
    def get_queryset(self):
        return New.objects.all().order_by('-unique_id')


class NewDetailAPIView(generics.ListAPIView):
    queryset = New.objects.all()
    serializer_class = NewModelSerializer

    def get_queryset(self, *args, **kwargs):
        id = self.kwargs.get("pk")
        qs = New.objects.filter(pk=id)
        return qs

ChuangShun/src/nba_news/views.py
from django.shortcuts import render
from django.views import View

from .models import New
import requests
from bs4 import BeautifulSoup
import re

def nba(request):
    url = 'https://nba.udn.com/nba/index'
    NBA_hot = requests.get(url)
    NBA_hot.encoding='utf-8'
    NBA_hot_soup = BeautifulSoup(NBA_hot.text, 'html.parser')
    NBA_hot_list = NBA_hot_soup.findAll('div', attrs={'id': 'news', 'class':'box'})
    NBA_hot_list2 = NBA_hot_list[0].findAll('dt')
    show = []
    for host_list in NBA_hot_list2:
        obj = {}
        temp = host_list.find('a')
        url = "https://nba.udn.com/" + temp['href']
        NBA_detail = requests.get(url)
        NBA_detail.encoding='utf-8'
        NBA_detail_soup = BeautifulSoup(NBA_detail.text, 'html.parser')

        findID = NBA_detail_soup.find('div', attrs={'id' : 'story_body'})
        obj['article_id'] = findID['data-article']

        total = NBA_detail_soup.find('div', attrs={'id' : 'story_body_content'})

        obj['title'] = total.find('h1', attrs={'class':'story_art_title'}).text

        image = total.findAll( 'img', {})
        obj['imagelink'] = image[0]['data-src']
        content = total.findAll('p')
        content[0].find('div', {'class':'only_web'}).decompose()
        obj['content'] = content[0].text
        if New.objects.filter( unique_id = obj['article_id']) :
            print( 'Exist' )
            pass
        else:
            New.objects.create( unique_id = obj['article_id'], title = obj['title'],
                            content= obj['content'], image_link = obj['imagelink'] )
            show.append(obj)
            print('Success add a article')

    return render(request, "nba_news/NBA.html", {"obj": show })

ChuangShun/src/web_scraping/views.py
from django.shortcuts import render, get_object_or_404
import requests
from nba_news.models import New

def home(request):
    qs = New.objects.all().order_by('-unique_id')
    context = {
        "objects_list" : qs
    }
    return render(request, "home.html", context)

def detail(request, id=None):
    instance = get_object_or_404( New , unique_id= id)
    context = {
        "list" : instance
    }
    return render(request, "detail.html", context)

ChuangShun/src/nba_news/templates/nba_news/NBA.html
{% extends "base.html" %}

 {% block begin %}

{% if obj %}
<br>
<h1> New article </h1><br>

{% for list in obj %}
<hr>
<div class="col-md-10 col-xs-12">
  <div class="card border">

    <div class="card-block">
      <h3> {{ list.title }}      </h3>
      <h3> Article ID : {{ list.article_id }} </h3>
      <hr>
    </div>
    <div class="card-block">
      <img src={{ list.imagelink }} alt="" title="" width="500px" height="300px">
      <br><br><br> {{ list.content }} <br><br>
    </div>
  </div>
</div>
<hr>
{% endfor %}

{% else %}
<br>
<h1> Sorry,  焦點文章皆已更新至資料庫</h1> {% endif%}

{% endblock begin %}

ChuangShun/src/templates/base.html
 {% load static %}

<!DOCTYPE HTML>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <title>Nick's web</title>
  <link href="{% static 'static/css/custom.css' %}" rel="stylesheet">

  <link href="{% static 'static/css/font-awesome.min.css' %}" rel="stylesheet">
  <!-- <link href="{% static 'images/thumbs' %}" rel="stylesheet"> -->
  <!-- Bootstrap -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

  <style>
    .border {
      padding: 5px;
      border-style: groove;
      border-color: #d3d6d7;
      padding: 10px;
      margin: 10px;
    }

    .customer {
      margin-top: 30px;
      margin-right: 30px;
      margin-bottom: 10px;
    }

    .customer_link {
      margin-right: 30px;
    }
  </style>

{% include "navbar.html" %}
<body style="padding-top:50px; background-color:#eff7fb">
  <div class='container'>
  {% block begin %} {% endblock begin %}
  </div>


  {% block script %}{% endblock script %}

  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> -->
</body>

</html>

ChuangShun/src/templates/detail.html
{% extends "base.html" %}
{% load static %}
{% block script %}
<script>
$(document).ready(function(){
  console.log('')
  var Newlist = [];

  function attachNew(value){
    var title = value.title;
    var id = value.unique_id;
    var content = value.content;
    var image_link = value.image_link;
    var date = value.date_display;
    $("#news-list").append(
  "<br/><br/><div class=\"col-md-10 col-xs-12\"><div class=\"card border\"><div class=\"card-block\"><h3>"+ title +"</h3><h3> Article ID :"+ id +"</h3><hr></div><div class=\"card-block\"><img src=" +image_link  +"alt=\"\" title=\"\" width=\"500px\" height=\"300px\"><br><br><br>"+ content +"<br><br></div></div></div><br/><br/>"
  )
  }

  function parseNews(){
     $.each(Newlist, function(key, value){
          attachNew(value)
      })
  }
  function fetchSingleNew( id ){
    var fecthDetailUrl = '/api/nba-news/' + id + '/'
   $.ajax({
     url: fecthDetailUrl,
     method: "GET",
     success: function(data){
     Newlist = data
     parseNews()
     },
     error: function(data){
       console.log("error")
       console.log(data)
     }
   })
  }
  fetchSingleNew( {{ list.unique_id }} )
  });

</script>
{% endblock script %}


{% block begin %}

<div id='news-list'>

</div>

<!-- <div class="col-md-10 col-xs-12"> -->
  <!-- <div class="card border"> -->

    <!-- <div class="card-block"> -->
      <!-- <h3> {{ list.title }} </h3> -->
      <!-- <h3> Article ID : {{ list.unique_id }} </h3> -->
      <!-- <hr> -->
    <!-- </div> -->

    <!-- <div class="card-block"> -->
      <!-- <img src={{ list.image_link }}  alt="" title="" width="500px" height="300px"> -->
      <!-- <br><br><br> {{ list.content }} <br><br> -->
    <!-- </div> -->
  <!-- </div> -->
<!-- </div> -->

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> -->

{% endblock begin %}

ChuangShun/src/templates/home.html
{% extends "base.html" %}
{% load static %}


{% block script %}
<script>
$(document).ready(function(){
  var nextNewUrl;
  var NewList = [];

 function attachNew(value){
   var title = value.title;
   var id = value.unique_id;
   var content = value.content;
   var image_link = value.image_link;
   var date = value.date_display;

   $("#news-list").append(
 "<div class=\"col-md-6 col-xs-12\"><div class=\"card border\"><div class=\"card-block\"><h3><a style='color:#b22222' href= '/detail/" +id  +"'>"
 +title +"</a><br/></h3><h3> Article ID : " +id +"<br/><br/> <input class=\'btn btn-primary pull-right\' style='background-color:#114166; top:-30px; right: 20px; position: relative; ' type=\"submit\" onclick= \"location.href='/detail/" +id + "';\" value=\"View\"/>" +"</div></div></div>"
)
 }

 function parseNews(){
   if (NewList == 0) {
     $("#news-list").text("No NEWS currently found.")
   } else {
    $.each(NewList, function(key, value){
         attachNew(value)
     })
   }
 }

 function fetchNews(url){
     var fecthUrl;
     if (!url) {
       fecthUrl = "/api/nba-news/"
     } else {
       fecthUrl = url
     }
  $.ajax({
    url: fecthUrl,
    method: "GET",
    success: function(data){
      NewList = data.results
      if (data.next){
        nextNewUrl = data.next
      } else {
        $("#loadmore").css("display", "none")
      }
    parseNews()
    },
    error: function(data){
      console.log("error")
      console.log(data)
    }
  })
}

fetchNews()

  $("#loadmore").click(function(event){
    event.preventDefault()
    if (nextNewUrl) {
      fetchNews(nextNewUrl)
    }
})

});
</script>
{% endblock script %}



{% block begin %}
<div>
    <br><h1>焦點新聞列表</h1><br>

    <div id='news-list'>

    </div>
    <div class="container " style="line-height: 5;">
      <a style='font-size: 150%; color: #696969' href='#' id='loadmore'> More News </a><br><br><br><br>
    </div>
</div>
    <!-- {% for list in objects_list%} -->
    <!-- <div class="col-md-6 col-xs-12"> -->
      <!-- <div class="card border"> -->

        <!-- <div class="card-block"> -->

          <!-- <h3><a href= '{{ list.get_absolute_url }}' >{{ list.title }}</a><br/></h3> -->

          <!-- <h3> Article ID : {{ list.unique_id }} </h3> -->
          <!-- <hr> -->
        <!-- </div> -->

      <!-- </div> -->
    <!-- </div> -->
    <!-- {% endfor %} -->

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
      <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> -->



{% endblock begin %}

ChuangShun/src/templates/navbar.html
<nav class="navbar-inverse navbar-fixed-top navbar-default" >
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'home' %}">Nick</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'nba-news:nba' %}">Update article</a></li>
      </ul>
    </div>
  </div>
 </nav>